controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    # config/routes.yaml

index:
    path: /
    controller: App\Controller\singin/index.html.twig::index
    methods: ['GET']

